=== silky/lhcb-physics/Sim/Gauss/xml/Simulation.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Main node
     It contains 3 subnodes : the definition of the Simulation attributes,
     The association of these attributes to materials and the association of
     these attributes to volumes -->
<!ELEMENT Simulation (SimAtts, LogVols, ProductionCuts, Regions)>
<!ATTLIST Simulation DTD_Version CDATA #FIXED "v1">

<!-- The definitions of Simulation attributes -->
<!ELEMENT SimAtts (SimAtt*)>

<!-- Simulation attribute definition. This has a name and
     defines the way a volume should be simulated. The possible
     customization are :
        - the maximum number of steps
        - the maximum track length
        - the maximum time
        - the minimal kinetic energy
        - the minimal remaining range -->
<!ELEMENT SimAtt EMPTY>
<!ATTLIST SimAtt
         name ID #REQUIRED
         maxAllowedStep CDATA #IMPLIED
         maxTrackLength CDATA #IMPLIED
         maxTime        CDATA #IMPLIED
         minEkine       CDATA #IMPLIED
         minRange       CDATA #IMPLIED>

<!-- Association of sets and logical volumes -->
<!ELEMENT LogVols (Item*)>

<!ELEMENT Item (Cut*)>
<!ATTLIST Item
        name CDATA #REQUIRED>

<!ELEMENT Cut EMPTY>
<!ATTLIST Cut
        particle CDATA #REQUIRED
        attr CDATA #REQUIRED>

<!-- The part below deals with production cuts per region (WP) -->

<!ELEMENT ProductionCuts (ProductionCut*)>

<!ELEMENT ProductionCut EMPTY>
<!ATTLIST ProductionCut
         name           ID #REQUIRED
         gammaCut       CDATA #IMPLIED
         electronCut    CDATA #IMPLIED
         positronCut    CDATA #IMPLIED
         protonCut      CDATA #IMPLIED
         antiProtonCut  CDATA #IMPLIED
         neutronCut     CDATA #IMPLIED
         antiNeutronCut CDATA #IMPLIED>

<!ELEMENT Regions (Region*)>

<!ELEMENT Region (Volume*)>
<!ATTLIST Region
         name           ID #REQUIRED
         prodcut        CDATA #REQUIRED>

<!ELEMENT Volume EMPTY>
<!ATTLIST Volume
          name           CDATA #REQUIRED>

=== silky/lhcb-physics/Sim/Gauss/xml/Simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Simulation SYSTEM "Simulation.dtd">
  <Simulation>
  <SimAtts>
    
    <!-- ******************************************************************* -->
    <!-- This part of the file contains definitions of simulation attributes -->
    <!-- ******************************************************************* -->
    
    <SimAtt name="SimAttrGlobal"
      minEkine="1.0*MeV"/>

    <SimAtt name="SimAttrMuFilt"
      minEkine="500.0*MeV"/>

    <SimAtt name="SimAttrMuon"
      minEkine="10.0*MeV"/>
    
    <SimAtt name="SimAttrElectr"
      minEkine="0.001*MeV"/>
    <!-- the following is to avoid tracking in the shielding. SE July24 2003
         set it to default -->
    <SimAtt name="SimAttrShielding"
        minEkine="1.0*GeV" /> 
 
    <!-- Note that you may skip some of the attributes ! -->
    
  </SimAtts>
  <LogVols>
    
    <!-- ************************************************************** -->
    <!-- This part is where simulation attributes are mapped to volumes -->
    <!-- ************************************************************** -->

    <Item name="/dd/Geometry/Rich1/lvRich1MgsOuterH0">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsOuterH1">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsUpstrH0">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsUpstrH1">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsDnstrH0">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsDnstrH1">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsSide">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsMidH0">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRich1MgsMidH1">
      <Cut particle="0" attr="SimAttrShielding"/>    
    </Item>
    <Item name="/dd/Geometry/Rich1/lvRichHPDMaster">
      <Cut particle="0" attr="SimAttrGlobal"/>
      <Cut particle="11" attr="SimAttrElectr"/>
    </Item>

    <Item name="/dd/Geometry/Muon/lvMuFilter1">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/Muon/lvMuFilter2">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/Muon/lvMuFilter3">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/Muon/lvMuFilter4">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>
    
  </LogVols>

  <!-- Define cuts to be applied later in regions -->
  <ProductionCuts>
    <ProductionCut name="calocut"
      gammaCut="10*MeV"/>
  </ProductionCuts>

  <!-- Example of definition of cuts for a set of logical volume -->
  <Regions>
    <Region name="calos" prodcut="calocut"> 
      <Volume name="/dd/Geometry/HCal..."/>
    </Region> 
  </Regions>   
  
  </Simulation>

=== silky/lhcb-physics/gauss/Sim/Gauss/xml/Simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Simulation SYSTEM "Simulation.dtd"[
<!ENTITY SimAttrRich SYSTEM "RichSimulationAttributes.xml">
<!ENTITY RegionDefRich1Aerogel SYSTEM "Rich1AerogelRegionDefinition.xml">
<!ENTITY RegionDefRichOverall SYSTEM "RichOverallRegionDefinition.xml">
]>
  <Simulation>
  <SimAtts>
    
    <!-- ******************************************************************* -->
    <!-- This part of the file contains definitions of simulation attributes -->
    <!-- ******************************************************************* -->
    
    <SimAtt name="SimAttrGlobal"
      minEkine="1.0*MeV"/>

    <SimAtt name="SimAttrMuFilt"
      minEkine="500.0*MeV"/>

    <SimAtt name="SimAttrMuon"
      minEkine="10.0*MeV"/>
    
    <SimAtt name="SimAttrElectr"
      minEkine="0.001*MeV"/>
    <!-- the following not used. This is so that the default 
         thresholds for the  magnet iron is used also for the
         RichShielding -->
    <SimAtt name="SimAttrShielding"
        minEkine="1.0*MeV" /> 
 
    <!-- Note that you may skip some of the attributes ! -->
    
  </SimAtts>
  <LogVols>
    
    <!-- ************************************************************** -->
    <!-- This part is where simulation attributes are mapped to volumes -->
    <!-- ************************************************************** -->

    &SimAttrRich;

    <Item name="/dd/Geometry/DownstreamRegion/Muon/lvMuFilter1">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/DownstreamRegion/Muon/lvMuFilter2">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/DownstreamRegion/Muon/lvMuFilter3">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>

   <Item name="/dd/Geometry/DownstreamRegion/Muon/lvMuFilter4">
      <Cut particle="0" attr="SimAttrMuFilt"/>
      <Cut particle="13" attr="SimAttrMuon"/>
      <Cut particle="-13" attr="SimAttrMuon"/>
    </Item>
    
  </LogVols>

  <!-- Define cuts to be applied later in regions -->
  <ProductionCuts>
    <ProductionCut name="calocut"
      gammaCut="10*MeV"/>


  <!-- Produce delta electrons in RICH above the 
       Cherenkov Threshold for electrons in the medium .
       Three regions considered : (a) aerogel , (b) rich1 submaster
       (c) rich2 master
       The Rich1Overall region contains the aerogel region 
       and hence if OverallRich region is activated there is no need to
       activate the aerogel region separately in this file.

       For now, only the aerogel region is activated until
       the effect on the cpu time is verified SE 2-11-2005 
    <ProductionCut name="Rich1OverallDeltaElectronCut"
      electronCut="1.5*mm"/>
    <ProductionCut name="Rich2OverallDeltaElectronCut"
      electronCut="1.5*mm"/>
-->

  <ProductionCut name="RichAerogelDeltaElectronCut"
      electronCut="1.5*mm"
      positronCut="5.0*mm"
      gammaCut="10.0*mm"/>
  </ProductionCuts>

  <Regions>

    &RegionDefRich1Aerogel;

    <!-- @RegionDefRichOverall; -->

  </Regions>  
  
  </Simulation>
